// Mock "Cortex Assist" API - a fictional multi-agent RAG chat platform.
// This exists so the whole benchmark framework runs end-to-end with zero
// external dependencies: no real backend, no real credentials needed.
//
// It deliberately reproduces the two "gotchas" that shaped this framework's
// design (see README):
//   1. POST /api/chats/create only accepts multipart/form-data - a JSON
//      body is rejected outright here (400), instead of the silent-failure
//      behavior a real backend might have. Teaches the same lesson faster.
//   2. POST /api/conversation/stream returns newline-delimited JSON over a
//      chunked response (NOT Server-Sent Events), and can report an
//      application-level error while still returning HTTP 200.
//
// Answers are generated by matching the incoming question against
// datasets/Acme_Benchmark_Dataset.xlsx and returning a mix of correct,
// degraded, and "not found" responses - so a benchmark run against it
// produces a realistic, non-trivial pass/fail distribution instead of a
// suspicious 100%.
const express = require("express");
const multer = require("multer");
const path = require("path");
const crypto = require("crypto");
const XLSX = require("xlsx");
const agents = require("./agents");
const { resolveAgentKey } = require("../scripts/datasetIO");

const PORT = process.env.MOCK_SERVER_PORT || 4000;
const upload = multer();
const app = express();
app.use(express.json());

// ---------------------------------------------------------------------
// Load the sample dataset into a per-agent question -> answer lookup
// ---------------------------------------------------------------------
const DATASET_PATH = path.join(__dirname, "..", "datasets", "Acme_Benchmark_Dataset.xlsx");
const knowledgeBase = {}; // agentKey -> [{ question, answer, source }]

function loadKnowledgeBase() {
  const wb = XLSX.readFile(DATASET_PATH);
  for (const sheetName of wb.SheetNames) {
    const rows = XLSX.utils.sheet_to_json(wb.Sheets[sheetName], { defval: "" });
    for (const row of rows) {
      const agentKey = resolveAgentKey(row["Agent"]);
      const question = row["Question"];
      const answer = row["Expected Answer"];
      if (!agentKey || !question || !answer) continue;
      if (!knowledgeBase[agentKey]) knowledgeBase[agentKey] = [];
      knowledgeBase[agentKey].push({ question, answer, source: row["Source Document"] || "Acme Corp Handbook" });
    }
  }
  const counts = Object.fromEntries(Object.entries(knowledgeBase).map(([k, v]) => [k, v.length]));
  console.log("Loaded knowledge base:", counts);
}
loadKnowledgeBase();

function normalize(text) {
  return String(text)
    .toLowerCase()
    .replace(/[^a-z0-9 ]/g, " ")
    .split(/\s+/)
    .filter(Boolean);
}

function bestMatch(agentKey, query) {
  const entries = knowledgeBase[agentKey] || [];
  if (entries.length === 0) return null;

  const queryWords = new Set(normalize(query));
  let best = null;
  let bestScore = 0;

  for (const entry of entries) {
    const entryWords = new Set(normalize(entry.question));
    let overlap = 0;
    for (const w of queryWords) if (entryWords.has(w)) overlap++;
    const score = overlap / Math.max(queryWords.size, entryWords.size);
    if (score > bestScore) {
      bestScore = score;
      best = entry;
    }
  }

  return bestScore >= 0.35 ? best : null;
}

// Simulates realistic agent behavior: mostly correct, sometimes degraded
// (drops a clause), sometimes a hallucinated wrong answer, sometimes a
// genuine "not found" - so a benchmark run has a believable pass rate
// instead of a suspicious 100%.
function generateAnswer(agentKey, query) {
  const match = bestMatch(agentKey, query);
  if (!match) {
    return {
      text: "I'm sorry, I couldn't find information about that in the available knowledge base. Could you rephrase the question or provide more detail?",
      references: [],
    };
  }

  const roll = Math.random();
  const reference = {
    index: 1,
    chunk: match.answer,
    source: match.source,
    knowledge_name: `${agentKey}_Knowledge_Base`,
  };

  if (roll < 0.72) {
    // Correct
    return { text: `${match.answer} [1]`, references: [reference] };
  }

  if (roll < 0.86) {
    // Degraded: truncate to first clause/sentence, dropping detail
    const truncated = match.answer.split(/(?<=[.;])\s/)[0];
    return { text: `${truncated} [1]`, references: [reference] };
  }

  // Hallucinated / off-target: answer a nearby question instead, or hedge
  const entries = knowledgeBase[agentKey] || [];
  const other = entries[Math.floor(Math.random() * entries.length)];
  return {
    text: other && other.question !== match.question
      ? `${other.answer} [1]`
      : "I have some general information on this topic, but I'm not fully certain of the exact policy details - please confirm with your manager or the relevant department.",
    references: [reference],
  };
}

function accuracyFor(roll) {
  return Math.round(roll * 100);
}

// ---------------------------------------------------------------------
// Routes
// ---------------------------------------------------------------------

app.get("/api/agents/getAllAgents", (req, res) => {
  res.json({ data: Object.entries(agents).map(([key, a]) => ({ id: a.id, name: a.name, key })) });
});

app.post("/auth/login", (req, res) => {
  const { email, password, key } = req.body || {};
  if (!email || !password || !key) {
    return res.status(400).json({ status: "error", message: "email, password, and key are required" });
  }
  const token = Buffer.from(JSON.stringify({ sub: email, iat: Date.now() })).toString("base64url");
  res.status(201).json({
    status: "success",
    access_token: `mock.${token}.signature`,
    refresh_token: `mock-refresh.${token}.signature`,
  });
});

// Deliberately mirrors a real integration lesson: this endpoint only
// accepts multipart/form-data. A JSON body is rejected outright (rather
// than silently accepted-but-ignored) so the failure mode is obvious.
app.post("/api/chats/create", upload.none(), (req, res) => {
  if (!req.is("multipart/form-data")) {
    return res.status(400).json({
      status: "error",
      message: "chats/create requires multipart/form-data (field: selectedAgentId), not JSON",
    });
  }

  const { selectedAgentId } = req.body || {};
  const agentEntry = Object.values(agents).find((a) => a.id === selectedAgentId);
  if (!agentEntry) {
    return res.status(404).json({ status: "error", message: `Unknown agent id: ${selectedAgentId}` });
  }

  res.status(201).json({
    id: crypto.randomUUID(),
    title: "New Chat",
    context: "aiAgent",
    agentId: selectedAgentId,
    agentVoiceId: "US",
  });
});

// Streams newline-delimited JSON (NOT Server-Sent Events) over a chunked
// response: keep_alive -> references -> metrics -> answer. Can report an
// application-level error inside the stream while still returning HTTP 200,
// mirroring real-world "status is not a reliable success signal" behavior.
app.post("/api/conversation/stream", express.json(), async (req, res) => {
  const { query, agent_id } = req.body || {};
  const agentKey = Object.keys(agents).find((k) => agents[k].id === agent_id);

  res.status(200);
  res.setHeader("Content-Type", "text/plain");
  res.setHeader("Transfer-Encoding", "chunked");
  res.setHeader("Cache-Control", "no-cache");

  const write = (obj) => res.write(JSON.stringify(obj) + "\n");

  write({ type: "keep_alive", model_name: "system", content: "" });
  await new Promise((r) => setTimeout(r, 150 + Math.random() * 250));

  if (!agentKey) {
    write({
      type: "answer",
      model_name: "system",
      content: "Service was unavailable",
      error: true,
      message: "AI service error: 404 Not Found",
    });
    return res.end();
  }

  const roll = Math.random();
  const { text, references } = generateAnswer(agentKey, query || "");

  write({ type: "references", model_name: "cortex/assist-1", content: references });
  write({
    type: "metrics",
    model_name: "cortex/assist-1",
    content: { non_compliant: roll > 0.85, privacy_policy_violation: false, accuracy: accuracyFor(roll) },
  });
  write({ type: "answer", model_name: "cortex/assist-1", content: text });
  res.end();
});

app.listen(PORT, () => {
  console.log(`Mock Cortex Assist API listening on http://localhost:${PORT}`);
});
